name: k6 with Webpack

on:
  push:
    branches: [ "rajeshm-grafanak6-patch-1" ]
  pull_request:
    branches: [ "rajeshm-grafanak6-patch-1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: Run k6 tests
        run: |
          npm run smoke_test
